export const STOP_ROUTINE_REQUEST = 'ROUTINES.STOP_ROUTINE_REQUEST'
export const STOP_ROUTINE_FAILURE = 'ROUTINES.STOP_ROUTINE_FAILURE'
export const STOP_ROUTINE_SUCCESS = 'ROUTINES.STOP_ROUTINE_SUCCESS'

export const START_ROUTINE_REQUEST = 'ROUTINES.START_ROUTINE_REQUEST'
export const START_ROUTINE_FAILURE = 'ROUTINES.START_ROUTINE_FAILURE'
export const START_ROUTINE_SUCCESS = 'ROUTINES.START_ROUTINE_SUCCESS'

export const FETCH_ROUTINES_REQUEST = 'ROUTINES.FETCH_ROUTINES_REQUEST'
export const FETCH_ROUTINES_FAILURE = 'ROUTINES.FETCH_ROUTINES_FAILURE'
export const FETCH_ROUTINES_SUCCESS = 'ROUTINES.FETCH_ROUTINES_SUCCESS'

export const CREATE_ROUTINE_REQUEST = 'ROUTINES.CREATE_ROUTINE_REQUEST'
export const CREATE_ROUTINE_FAILURE = 'ROUTINES.CREATE_ROUTINE_FAILURE'
export const CREATE_ROUTINE_SUCCESS = 'ROUTINES.CREATE_ROUTINE_SUCCESS'

export const UPDATE_ROUTINE_REQUEST = 'ROUTINES.UPDATE_ROUTINE_REQUEST'
export const UPDATE_ROUTINE_FAILURE = 'ROUTINES.UPDATE_ROUTINE_FAILURE'
export const UPDATE_ROUTINE_SUCCESS = 'ROUTINES.UPDATE_ROUTINE_SUCCESS'

export const DESTROY_ROUTINE_REQUEST = 'ROUTINES.DESTROY_ROUTINE_REQUEST'
export const DESTROY_ROUTINE_FAILURE = 'ROUTINES.DESTROY_ROUTINE_FAILURE'
export const DESTROY_ROUTINE_SUCCESS = 'ROUTINES.DESTROY_ROUTINE_SUCCESS'
