export const STOP_ROUTINE_REQUEST = 'ROUTINES.STOP_ROUTINE_REQUEST'
export const STOP_ROUTINE_FAILURE = 'ROUTINES.STOP_ROUTINE_FAILURE'
export const STOP_ROUTINE_SUCCESS = 'ROUTINES.STOP_ROUTINE_SUCCESS'

export const START_ROUTINE_REQUEST = 'ROUTINES.START_ROUTINE_REQUEST'
export const START_ROUTINE_FAILURE = 'ROUTINES.START_ROUTINE_FAILURE'
export const START_ROUTINE_SUCCESS = 'ROUTINES.START_ROUTINE_SUCCESS'

export const FETCH_REQUEST = 'ROUTINES.FETCH_REQUEST'
export const FETCH_FAILURE = 'ROUTINES.FETCH_FAILURE'
export const FETCH_SUCCESS = 'ROUTINES.FETCH_SUCCESS'

export const FETCH_ROUTINES_REQUEST = 'ROUTINES.FETCH_ROUTINES_REQUEST'
export const FETCH_ROUTINES_FAILURE = 'ROUTINES.FETCH_ROUTINES_FAILURE'
export const FETCH_ROUTINES_SUCCESS = 'ROUTINES.FETCH_ROUTINES_SUCCESS'

export const CREATE_ROUTINE_REQUEST = 'ROUTINES.CREATE_ROUTINE_REQUEST'
export const CREATE_ROUTINE_FAILURE = 'ROUTINES.CREATE_ROUTINE_FAILURE'
export const CREATE_ROUTINE_SUCCESS = 'ROUTINES.CREATE_ROUTINE_SUCCESS'

export const UPDATE_ROUTINE_REQUEST = 'ROUTINES.UPDATE_ROUTINE_REQUEST'
export const UPDATE_ROUTINE_FAILURE = 'ROUTINES.UPDATE_ROUTINE_FAILURE'
export const UPDATE_ROUTINE_SUCCESS = 'ROUTINES.UPDATE_ROUTINE_SUCCESS'

export const DESTROY_ROUTINE_REQUEST = 'ROUTINES.DESTROY_ROUTINE_REQUEST'
export const DESTROY_ROUTINE_FAILURE = 'ROUTINES.DESTROY_ROUTINE_FAILURE'
export const DESTROY_ROUTINE_SUCCESS = 'ROUTINES.DESTROY_ROUTINE_SUCCESS'

export const SET_DATA_RANGE = 'ROUTINES.SET_DATA_RANGE'

export const SET_SELECTED_ROUTINE = 'ROUTINES.SET_SELECTED_ROUTINE'
export const CLEAR_SELECTED_ROUTINE = 'ROUTINES.CLEAR_SELECTED_ROUTINE'

export const CLEAR_SEARCH_TERM = 'ROUTINES.CLEAR_SEARCH_TERM'
export const SET_SEARCH_TERM = 'ROUTINES.SET_SEARCH_TERM'

export const UPSERT_START_CREATION = 'ROUTINES.UPSERT_START_CREATION'
export const UPSERT_START_EDITION = 'ROUTINES.UPSERT_START_EDITION'

export const UPSERT_SET_CURRENT_SECTION = 'ROUTINES.UPSERT_SET_CURRENT_SECTION'

export const UPSERT_UPDATE_ROUTINE = 'ROUTINES.UPSERT_UPDATE_ROUTINE'

export const UPSERT_ADD_TEMPERATURE_RANGE = 'ROUTINES.UPSERT_ADD_TEMPERATURE_RANGE'
export const UPSERT_SET_TEMPERATURE_RANGE = 'ROUTINES.UPSERT_SET_TEMPERATURE_RANGE'
export const UPSERT_REMOVE_TEMPERATURE_RANGE = 'ROUTINES.UPSERT_REMOVE_TEMPERATURE_RANGE'

export const UPSERT_SUBMIT = 'ROUTINES.UPSERT_SUBMIT'
