export const ADD_READING = 'READINGS.ADD_READING'

export const CREATE_EXTERNAL_READING_REQUEST = 'READINGS.CREATE_EXTERNAL_READING_REQUEST'
export const CREATE_EXTERNAL_READING_FAILURE = 'READINGS.CREATE_EXTERNAL_READING_FAILURE'
export const CREATE_EXTERNAL_READING_SUCCESS = 'READINGS.CREATE_EXTERNAL_READING_SUCCESS'

export const FETCH_ROUTINE_READINGS_REQUEST = 'READINGS.FETCH_ROUTINE_READINGS_REQUEST'
export const FETCH_ROUTINE_READINGS_FAILURE = 'READINGS.FETCH_ROUTINE_READINGS_FAILURE'
export const FETCH_ROUTINE_READINGS_SUCCESS = 'READINGS.FETCH_ROUTINE_READINGS_SUCCESS'
