export const PUSH_ACID_REQUEST = 'PUMP_CALIBRATION.PUSH_ACID_REQUEST'
export const PUSH_ACID_FAILURE = 'PUMP_CALIBRATION.PUSH_ACID_FAILURE'
export const PUSH_ACID_SUCCESS = 'PUMP_CALIBRATION.PUSH_ACID_SUCCESS'

export const TEST_ACID_DROP_REQUEST = 'PUMP_CALIBRATION.TEST_ACID_DROP_REQUEST'
export const TEST_ACID_DROP_FAILURE = 'PUMP_CALIBRATION.TEST_ACID_DROP_FAILURE'
export const TEST_ACID_DROP_SUCCESS = 'PUMP_CALIBRATION.TEST_ACID_DROP_SUCCESS'

export const PUSH_BASE_REQUEST = 'PUMP_CALIBRATION.PUSH_BASE_REQUEST'
export const PUSH_BASE_FAILURE = 'PUMP_CALIBRATION.PUSH_BASE_FAILURE'
export const PUSH_BASE_SUCCESS = 'PUMP_CALIBRATION.PUSH_BASE_SUCCESS'

export const TEST_BASE_DROP_REQUEST = 'PUMP_CALIBRATION.TEST_BASE_DROP_REQUEST'
export const TEST_BASE_DROP_FAILURE = 'PUMP_CALIBRATION.TEST_BASE_DROP_FAILURE'
export const TEST_BASE_DROP_SUCCESS = 'PUMP_CALIBRATION.TEST_BASE_DROP_SUCCESS'
