export const ADD_READING = 'READINGS.ADD_READING'

export const FETCH_ROUTINE_READINGS_REQUEST = 'READINGS.FETCH_ROUTINE_READINGS_REQUEST'
export const FETCH_ROUTINE_READINGS_FAILURE = 'READINGS.FETCH_ROUTINE_READINGS_FAILURE'
export const FETCH_ROUTINE_READINGS_SUCCESS = 'READINGS.FETCH_ROUTINE_READINGS_SUCCESS'

export const MERGE_READINGS = 'READINGS.MERGE_READINGS'
