export const SIGN_IN_REQUEST = 'SESSION.SIGN_IN_REQUEST'
export const SIGN_IN_FAILURE = 'SESSION.SIGN_IN_FAILURE'
export const SIGN_IN_SUCCESS = 'SESSION.SIGN_IN_SUCCESS'

export const SIGN_OUT_REQUEST = 'SESSION.SIGN_OUT_REQUEST'
export const SIGN_OUT_FAILURE = 'SESSION.SIGN_OUT_FAILURE'
export const SIGN_OUT_SUCCESS = 'SESSION.SIGN_OUT_SUCCESS'
