export const START_PH_METER_CALIBRATION = 'PH_CALIBRATION.START_PH_METER_CALIBRATION'
export const FINISH_PH_METER_CALIBRATION = 'PH_CALIBRATION.FINISH_PH_METER_CALIBRATION'

export const SET_CURRENT_CALIBRATION = 'PH_CALIBRATION.SET_CURRENT_CALIBRATION'

export const START_CALIBRATION = 'PH_CALIBRATION.START_CALIBRATION'

export const CALIBRATION_FAILURE = 'PH_CALIBRATION.CALIBRATION_FAILURE'
export const CALIBRATION_SUCCESS = 'PH_CALIBRATION.CALIBRATION_SUCCESS'
